package com.whatie.ati.androiddemo.database.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whatie.ati.androiddemo.database.entity.DeviceDB;
import com.whatie.ati.androiddemo.database.entity.HomeDB;
import com.whatie.ati.androiddemo.database.entity.RoomDB;
import com.whatie.ati.androiddemo.database.entity.SharedDeviceDB;
import com.whatie.ati.androiddemo.database.entity.SharingDeviceDB;
import com.whatie.ati.androiddemo.database.entity.WifiDB;

import com.whatie.ati.androiddemo.database.greenDao.DeviceDBDao;
import com.whatie.ati.androiddemo.database.greenDao.HomeDBDao;
import com.whatie.ati.androiddemo.database.greenDao.RoomDBDao;
import com.whatie.ati.androiddemo.database.greenDao.SharedDeviceDBDao;
import com.whatie.ati.androiddemo.database.greenDao.SharingDeviceDBDao;
import com.whatie.ati.androiddemo.database.greenDao.WifiDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceDBDaoConfig;
    private final DaoConfig homeDBDaoConfig;
    private final DaoConfig roomDBDaoConfig;
    private final DaoConfig sharedDeviceDBDaoConfig;
    private final DaoConfig sharingDeviceDBDaoConfig;
    private final DaoConfig wifiDBDaoConfig;

    private final DeviceDBDao deviceDBDao;
    private final HomeDBDao homeDBDao;
    private final RoomDBDao roomDBDao;
    private final SharedDeviceDBDao sharedDeviceDBDao;
    private final SharingDeviceDBDao sharingDeviceDBDao;
    private final WifiDBDao wifiDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceDBDaoConfig = daoConfigMap.get(DeviceDBDao.class).clone();
        deviceDBDaoConfig.initIdentityScope(type);

        homeDBDaoConfig = daoConfigMap.get(HomeDBDao.class).clone();
        homeDBDaoConfig.initIdentityScope(type);

        roomDBDaoConfig = daoConfigMap.get(RoomDBDao.class).clone();
        roomDBDaoConfig.initIdentityScope(type);

        sharedDeviceDBDaoConfig = daoConfigMap.get(SharedDeviceDBDao.class).clone();
        sharedDeviceDBDaoConfig.initIdentityScope(type);

        sharingDeviceDBDaoConfig = daoConfigMap.get(SharingDeviceDBDao.class).clone();
        sharingDeviceDBDaoConfig.initIdentityScope(type);

        wifiDBDaoConfig = daoConfigMap.get(WifiDBDao.class).clone();
        wifiDBDaoConfig.initIdentityScope(type);

        deviceDBDao = new DeviceDBDao(deviceDBDaoConfig, this);
        homeDBDao = new HomeDBDao(homeDBDaoConfig, this);
        roomDBDao = new RoomDBDao(roomDBDaoConfig, this);
        sharedDeviceDBDao = new SharedDeviceDBDao(sharedDeviceDBDaoConfig, this);
        sharingDeviceDBDao = new SharingDeviceDBDao(sharingDeviceDBDaoConfig, this);
        wifiDBDao = new WifiDBDao(wifiDBDaoConfig, this);

        registerDao(DeviceDB.class, deviceDBDao);
        registerDao(HomeDB.class, homeDBDao);
        registerDao(RoomDB.class, roomDBDao);
        registerDao(SharedDeviceDB.class, sharedDeviceDBDao);
        registerDao(SharingDeviceDB.class, sharingDeviceDBDao);
        registerDao(WifiDB.class, wifiDBDao);
    }
    
    public void clear() {
        deviceDBDaoConfig.clearIdentityScope();
        homeDBDaoConfig.clearIdentityScope();
        roomDBDaoConfig.clearIdentityScope();
        sharedDeviceDBDaoConfig.clearIdentityScope();
        sharingDeviceDBDaoConfig.clearIdentityScope();
        wifiDBDaoConfig.clearIdentityScope();
    }

    public DeviceDBDao getDeviceDBDao() {
        return deviceDBDao;
    }

    public HomeDBDao getHomeDBDao() {
        return homeDBDao;
    }

    public RoomDBDao getRoomDBDao() {
        return roomDBDao;
    }

    public SharedDeviceDBDao getSharedDeviceDBDao() {
        return sharedDeviceDBDao;
    }

    public SharingDeviceDBDao getSharingDeviceDBDao() {
        return sharingDeviceDBDao;
    }

    public WifiDBDao getWifiDBDao() {
        return wifiDBDao;
    }

}
